/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StateMapRouteImport } from './routes/$state/map'
import { Route as StateDataIndexRouteImport } from './routes/$state/data/index'
import { Route as StateDataDistrictRouteImport } from './routes/$state/data/$district'
import { Route as StateDataDistrictAcCodeIndexRouteImport } from './routes/$state/data/$district/$acCode/index'
import { Route as StateDataDistrictAcCodePsLangRouteImport } from './routes/$state/data/$district/$acCode/ps/$lang'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StateMapRoute = StateMapRouteImport.update({
  id: '/$state/map',
  path: '/$state/map',
  getParentRoute: () => rootRouteImport,
} as any)
const StateDataIndexRoute = StateDataIndexRouteImport.update({
  id: '/$state/data/',
  path: '/$state/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const StateDataDistrictRoute = StateDataDistrictRouteImport.update({
  id: '/$state/data/$district',
  path: '/$state/data/$district',
  getParentRoute: () => rootRouteImport,
} as any)
const StateDataDistrictAcCodeIndexRoute =
  StateDataDistrictAcCodeIndexRouteImport.update({
    id: '/$acCode/',
    path: '/$acCode/',
    getParentRoute: () => StateDataDistrictRoute,
  } as any)
const StateDataDistrictAcCodePsLangRoute =
  StateDataDistrictAcCodePsLangRouteImport.update({
    id: '/$acCode/ps/$lang',
    path: '/$acCode/ps/$lang',
    getParentRoute: () => StateDataDistrictRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$state/map': typeof StateMapRoute
  '/$state/data/$district': typeof StateDataDistrictRouteWithChildren
  '/$state/data/': typeof StateDataIndexRoute
  '/$state/data/$district/$acCode/': typeof StateDataDistrictAcCodeIndexRoute
  '/$state/data/$district/$acCode/ps/$lang': typeof StateDataDistrictAcCodePsLangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$state/map': typeof StateMapRoute
  '/$state/data/$district': typeof StateDataDistrictRouteWithChildren
  '/$state/data': typeof StateDataIndexRoute
  '/$state/data/$district/$acCode': typeof StateDataDistrictAcCodeIndexRoute
  '/$state/data/$district/$acCode/ps/$lang': typeof StateDataDistrictAcCodePsLangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$state/map': typeof StateMapRoute
  '/$state/data/$district': typeof StateDataDistrictRouteWithChildren
  '/$state/data/': typeof StateDataIndexRoute
  '/$state/data/$district/$acCode/': typeof StateDataDistrictAcCodeIndexRoute
  '/$state/data/$district/$acCode/ps/$lang': typeof StateDataDistrictAcCodePsLangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$state/map'
    | '/$state/data/$district'
    | '/$state/data/'
    | '/$state/data/$district/$acCode/'
    | '/$state/data/$district/$acCode/ps/$lang'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$state/map'
    | '/$state/data/$district'
    | '/$state/data'
    | '/$state/data/$district/$acCode'
    | '/$state/data/$district/$acCode/ps/$lang'
  id:
    | '__root__'
    | '/'
    | '/$state/map'
    | '/$state/data/$district'
    | '/$state/data/'
    | '/$state/data/$district/$acCode/'
    | '/$state/data/$district/$acCode/ps/$lang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StateMapRoute: typeof StateMapRoute
  StateDataDistrictRoute: typeof StateDataDistrictRouteWithChildren
  StateDataIndexRoute: typeof StateDataIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$state/map': {
      id: '/$state/map'
      path: '/$state/map'
      fullPath: '/$state/map'
      preLoaderRoute: typeof StateMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$state/data/': {
      id: '/$state/data/'
      path: '/$state/data'
      fullPath: '/$state/data/'
      preLoaderRoute: typeof StateDataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$state/data/$district': {
      id: '/$state/data/$district'
      path: '/$state/data/$district'
      fullPath: '/$state/data/$district'
      preLoaderRoute: typeof StateDataDistrictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$state/data/$district/$acCode/': {
      id: '/$state/data/$district/$acCode/'
      path: '/$acCode'
      fullPath: '/$state/data/$district/$acCode/'
      preLoaderRoute: typeof StateDataDistrictAcCodeIndexRouteImport
      parentRoute: typeof StateDataDistrictRoute
    }
    '/$state/data/$district/$acCode/ps/$lang': {
      id: '/$state/data/$district/$acCode/ps/$lang'
      path: '/$acCode/ps/$lang'
      fullPath: '/$state/data/$district/$acCode/ps/$lang'
      preLoaderRoute: typeof StateDataDistrictAcCodePsLangRouteImport
      parentRoute: typeof StateDataDistrictRoute
    }
  }
}

interface StateDataDistrictRouteChildren {
  StateDataDistrictAcCodeIndexRoute: typeof StateDataDistrictAcCodeIndexRoute
  StateDataDistrictAcCodePsLangRoute: typeof StateDataDistrictAcCodePsLangRoute
}

const StateDataDistrictRouteChildren: StateDataDistrictRouteChildren = {
  StateDataDistrictAcCodeIndexRoute: StateDataDistrictAcCodeIndexRoute,
  StateDataDistrictAcCodePsLangRoute: StateDataDistrictAcCodePsLangRoute,
}

const StateDataDistrictRouteWithChildren =
  StateDataDistrictRoute._addFileChildren(StateDataDistrictRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StateMapRoute: StateMapRoute,
  StateDataDistrictRoute: StateDataDistrictRouteWithChildren,
  StateDataIndexRoute: StateDataIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
