/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StateMapRouteImport } from './routes/$state/map'
import { Route as StateDataIndexRouteImport } from './routes/$state/data/index'
import { Route as StateDataDistrictRouteImport } from './routes/$state/data/$district'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StateMapRoute = StateMapRouteImport.update({
  id: '/$state/map',
  path: '/$state/map',
  getParentRoute: () => rootRouteImport,
} as any)
const StateDataIndexRoute = StateDataIndexRouteImport.update({
  id: '/$state/data/',
  path: '/$state/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const StateDataDistrictRoute = StateDataDistrictRouteImport.update({
  id: '/$state/data/$district',
  path: '/$state/data/$district',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$state/map': typeof StateMapRoute
  '/$state/data/$district': typeof StateDataDistrictRoute
  '/$state/data/': typeof StateDataIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$state/map': typeof StateMapRoute
  '/$state/data/$district': typeof StateDataDistrictRoute
  '/$state/data': typeof StateDataIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$state/map': typeof StateMapRoute
  '/$state/data/$district': typeof StateDataDistrictRoute
  '/$state/data/': typeof StateDataIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$state/map' | '/$state/data/$district' | '/$state/data/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$state/map' | '/$state/data/$district' | '/$state/data'
  id:
    | '__root__'
    | '/'
    | '/$state/map'
    | '/$state/data/$district'
    | '/$state/data/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StateMapRoute: typeof StateMapRoute
  StateDataDistrictRoute: typeof StateDataDistrictRoute
  StateDataIndexRoute: typeof StateDataIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$state/map': {
      id: '/$state/map'
      path: '/$state/map'
      fullPath: '/$state/map'
      preLoaderRoute: typeof StateMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$state/data/': {
      id: '/$state/data/'
      path: '/$state/data'
      fullPath: '/$state/data/'
      preLoaderRoute: typeof StateDataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$state/data/$district': {
      id: '/$state/data/$district'
      path: '/$state/data/$district'
      fullPath: '/$state/data/$district'
      preLoaderRoute: typeof StateDataDistrictRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StateMapRoute: StateMapRoute,
  StateDataDistrictRoute: StateDataDistrictRoute,
  StateDataIndexRoute: StateDataIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
